### ISSUE TITLE
Cleanup hook fired at the beginning instead of at the end when using nested states

### ISSUE THREAD

**Issue by teksuo** [helmfile/helmfile#105]
### Operating system

Ubuntu 22 & Manjaro 

### Helmfile Version

0.144.0

### Helm Version

3.9.0

### Bug description

I have a helmfile with a global "cleanup" hook and a "postsync" and "postuninstall" hook per-release. Everything works like a charm for both "sync" and "destroy" commands and the "cleanup" hook is always executed after all the releases have been processed. 

However, when I start using nested states, the global "cleanup" hook for the "destroy" command gets executed at the beginning of the process, right after logging into the registry.

I honestly don't understand this behavior and I don't see it documented anywhere. 

Any insight will be welcome,

Thanks in advance

### Steps to reproduce

https://github.com/teksuo/helmfile-nested-hook-bug

**Comment by mumoshu** [comment]
@teksuo Hey! Thanks a lot for reporting. It's very unfortunately this isn't documented anywhere, but it's the expected behavior as of today.

Helmfile is designed around the idea that each sub-helmfile (i.e. nested state) is independent of the parent helmfile.yaml, and should be able to run directly. If the global cleanup was designed to be called after the nested states, it encourages the opposite. The same applies to environment values- environment values aren't automatically inherited down to the nested states, just to encourage you to make those independently runnable.

I'd guess you won't like it, but the best practice here is to repeat your global hooks config within every nested state. You'd want to make it DRY, so I'd suggest considering extracting the global hooks part from the helmfiles and load it by using `{{ readFile }}`.
