### ISSUE TITLE
Homebrew formula doesn't upgrades helm diff plugin

### ISSUE THREAD

**Issue by giuscri** [helmfile/helmfile#259]
### Operating system

macOS 12.4

### Helmfile Version

v0.145.2

### Helm Version

v3.9.2

### Bug description

helmfile now uses `helm diff --color` introduced in https://github.com/databus23/helm-diff/pull/343/files (helm diff v3.4.0). If one upgrades helmfile using Homebrew but doesn't manually upgrade the helm diff plugin helmfile will fail

**Comment by mumoshu** [comment]
@giuscri Hey! Thanks for reporting. Unfortunately, we assume it's user's responsibility to match helm-diff version to what's expected by helmfile and needed by your use-case.
Shall we just note about that in the documentation, or do you have any other suggestion?

**Comment by yxxhero** [comment]
@mumoshu I think we can add a subcommand to init and check plugins.

**Comment by mumoshu** [comment]
@yxxhero Sounds like a good idea 👍

**Comment by xiaomudk** [comment]
Please let me track this issue

**Comment by xiaomudk** [comment]
@yxxhero @mumoshu The following is my idea, can you help to review it?

Execute `helmfile init`: 
1. Check whether helm is installed, if not, let the user choose whether to install it, run `curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash` to install.
2. Check the helm version, if the version is low, let the user choose whether to upgrade
3. Check the helm plugin (helm diff, helm secrets), if it is not installed or the version is low, let the user choose whether to install or upgrade.

Possible problems:
1. Support may be problematic on windows system

Future features:
1. Create a helmfile project directory
2. Generate a helmfile.yml template

**Comment by yxxhero** [comment]
I think the initial idea is good. It has improved the user experience. Let's have a look at it together. @mumoshu @xiaomudk

**Comment by mumoshu** [comment]
@xiaomudk Thanks for the proposal!
Actually, Helmfile has been putting its best effort to provide Windows support and the fact that Helmfile doesn't rely on external commands other than kustomize, helm, and helm plugins are effects of that.
That said, it would be great if we could implement `helmfile init` without making it dependent on `curl` and `bash`. We might be able to use Go's standard HTTP library instead of `curl` and instead curling the installation script, we'd embed a well-known helm download URL within the helmfile binary and use it as a download source.
Does that sound good to you?

**Comment by xiaomudk** [comment]
@mumoshu  
I'm not worried about the file download, I'm more worried about the installation process under Windows, such as the installation path, the addition of environment variables, and so on.
My opinion is that the windows platform is detected, the download address of helm is displayed, and the user can install it by himself.
what about your suggestion?

**Comment by yxxhero** [comment]
@xiaomudk just do it.
