### ISSUE TITLE
exec requires absolute path to command files

### ISSUE THREAD

**Issue by kaldvelski** [helmfile/helmfile#623]
### Operating system

Windows 10

### Helmfile Version

0.149.0

### Helm Version

3.9.4

### Bug description

As of helmfile v 0.148.0, the `exec` function does not allow relative paths, which I believe is linked to the underlying implementation in Go and the behaviour described here: https://pkg.go.dev/os/exec

Providing an absolute path to `exec` does resolve the issue but isn't a practical solution.

### Example helmfile.yaml

test.yaml
```
releases:
  - name: test
    chart: charts/test-chart
    version: 1.0.0
    values:
      - execValue: {{ exec "test.bat" list }}
```
test.bat
```
echo "hello"
```

### Error message you've seen (if any)

```
panic: unexpected error: exec: "test.bat": cannot run executable found relative to current directory

goroutine 23 [running]:
github.com/helmfile/helmfile/pkg/helmexec.Output(0x14c7edc0, {0x0, 0x0, 0x0})
        /home/runner/work/helmfile/helmfile/pkg/helmexec/runner.go:96 +0xd30
github.com/helmfile/helmfile/pkg/tmpl.(*Context).EnvExec.func2()
        /home/runner/work/helmfile/helmfile/pkg/tmpl/context_funcs.go:177 +0x43
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x62
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa6
```

### Steps to reproduce

Run the template action on the above 

### Working Helmfile Version

0.147.0

**Comment by mumoshu** [comment]
Hey!
I believe we should follow the Go policy not to open up security holes.

The only possible way forward would be to let you run the executables contained within the predeclared directories, so that the admin can limit what commands can be executed.
That would need two changes. First, you need some envvar or a config field to let the admin declare which directories can be used to look for the executable. Second, you'd need another template function other than the `exec` which has access to the predeclared directories.

Assuming we use an envvar to declare the directories, and name the new template function `execLib`, we'd end up with something that you'd run helmfile like:

```
$ HELMFILE_EXEC_LIB=./mycommands helmfile template
```

`test.bat` would be placed at `./mycommands/test.bar` which is evaluated relative to the path to the `helmfile.yaml`.

The `helmfile.yaml` would look almost same as what @kaldvelski provided, except that the template function is now `execLib` instead of `exec`:

```
releases:
  - name: test
    chart: charts/test-chart
    version: 1.0.0
    values:
      - execValue: {{ execLib "test.bat" list }}
```

**Comment by mumoshu** [comment]
Can we probably just do `PATH=$(pwd)/mycommands helmfile template` today if you don't use sub-helmfiles? 🤔

**Comment by yxxhero** [comment]
> Can you probably just do `PATH=$(pwd)/mycommands helmfile template` today if you don't use sub-helmfiles? 🤔

@kaldvelski could you try to do this? I will close the issue. if you have more issues. please free to post new issues.
